#############################################################################
# Makefile for building: meego-app-email
# Generated by qmake (2.01a) (Qt 4.8.4) on: ?? ??? 6 10:25:29 2013
# Project:  meego-app-email.pro
# Template: subdirs
# Command: /usr/bin/qmake -o Makefile meego-app-email.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-lib \
		sub-plugin \
		sub-content

lib/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) lib/ || $(MKDIR) lib/ 
	cd lib/ && $(QMAKE) /var/tmp/portage/meego-extra/meego-app-email-0.2.9/work/meego-app-email-0.2.9/lib/lib.pro -o $(MAKEFILE)
sub-lib-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) lib/ || $(MKDIR) lib/ 
	cd lib/ && $(QMAKE) /var/tmp/portage/meego-extra/meego-app-email-0.2.9/work/meego-app-email-0.2.9/lib/lib.pro -o $(MAKEFILE)
sub-lib: lib/$(MAKEFILE) FORCE
	cd lib/ && $(MAKE) -f $(MAKEFILE)
sub-lib-make_default-ordered: lib/$(MAKEFILE) FORCE
	cd lib/ && $(MAKE) -f $(MAKEFILE) 
sub-lib-make_default: lib/$(MAKEFILE) FORCE
	cd lib/ && $(MAKE) -f $(MAKEFILE) 
sub-lib-make_first-ordered: lib/$(MAKEFILE) FORCE
	cd lib/ && $(MAKE) -f $(MAKEFILE) first
sub-lib-make_first: lib/$(MAKEFILE) FORCE
	cd lib/ && $(MAKE) -f $(MAKEFILE) first
sub-lib-all-ordered: lib/$(MAKEFILE) FORCE
	cd lib/ && $(MAKE) -f $(MAKEFILE) all
sub-lib-all: lib/$(MAKEFILE) FORCE
	cd lib/ && $(MAKE) -f $(MAKEFILE) all
sub-lib-clean-ordered: lib/$(MAKEFILE) FORCE
	cd lib/ && $(MAKE) -f $(MAKEFILE) clean
sub-lib-clean: lib/$(MAKEFILE) FORCE
	cd lib/ && $(MAKE) -f $(MAKEFILE) clean
sub-lib-distclean-ordered: lib/$(MAKEFILE) FORCE
	cd lib/ && $(MAKE) -f $(MAKEFILE) distclean
sub-lib-distclean: lib/$(MAKEFILE) FORCE
	cd lib/ && $(MAKE) -f $(MAKEFILE) distclean
sub-lib-install_subtargets-ordered: lib/$(MAKEFILE) FORCE
	cd lib/ && $(MAKE) -f $(MAKEFILE) install
sub-lib-install_subtargets: lib/$(MAKEFILE) FORCE
	cd lib/ && $(MAKE) -f $(MAKEFILE) install
sub-lib-uninstall_subtargets-ordered: lib/$(MAKEFILE) FORCE
	cd lib/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-lib-uninstall_subtargets: lib/$(MAKEFILE) FORCE
	cd lib/ && $(MAKE) -f $(MAKEFILE) uninstall
plugin/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) plugin/ || $(MKDIR) plugin/ 
	cd plugin/ && $(QMAKE) /var/tmp/portage/meego-extra/meego-app-email-0.2.9/work/meego-app-email-0.2.9/plugin/plugin.pro -o $(MAKEFILE)
sub-plugin-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) plugin/ || $(MKDIR) plugin/ 
	cd plugin/ && $(QMAKE) /var/tmp/portage/meego-extra/meego-app-email-0.2.9/work/meego-app-email-0.2.9/plugin/plugin.pro -o $(MAKEFILE)
sub-plugin: plugin/$(MAKEFILE) FORCE
	cd plugin/ && $(MAKE) -f $(MAKEFILE)
sub-plugin-make_default-ordered: plugin/$(MAKEFILE) sub-lib-make_default-ordered  FORCE
	cd plugin/ && $(MAKE) -f $(MAKEFILE) 
sub-plugin-make_default: plugin/$(MAKEFILE) FORCE
	cd plugin/ && $(MAKE) -f $(MAKEFILE) 
sub-plugin-make_first-ordered: plugin/$(MAKEFILE) sub-lib-make_first-ordered  FORCE
	cd plugin/ && $(MAKE) -f $(MAKEFILE) first
sub-plugin-make_first: plugin/$(MAKEFILE) FORCE
	cd plugin/ && $(MAKE) -f $(MAKEFILE) first
sub-plugin-all-ordered: plugin/$(MAKEFILE) sub-lib-all-ordered  FORCE
	cd plugin/ && $(MAKE) -f $(MAKEFILE) all
sub-plugin-all: plugin/$(MAKEFILE) FORCE
	cd plugin/ && $(MAKE) -f $(MAKEFILE) all
sub-plugin-clean-ordered: plugin/$(MAKEFILE) sub-lib-clean-ordered  FORCE
	cd plugin/ && $(MAKE) -f $(MAKEFILE) clean
sub-plugin-clean: plugin/$(MAKEFILE) FORCE
	cd plugin/ && $(MAKE) -f $(MAKEFILE) clean
sub-plugin-distclean-ordered: plugin/$(MAKEFILE) sub-lib-distclean-ordered  FORCE
	cd plugin/ && $(MAKE) -f $(MAKEFILE) distclean
sub-plugin-distclean: plugin/$(MAKEFILE) FORCE
	cd plugin/ && $(MAKE) -f $(MAKEFILE) distclean
sub-plugin-install_subtargets-ordered: plugin/$(MAKEFILE) sub-lib-install_subtargets-ordered  FORCE
	cd plugin/ && $(MAKE) -f $(MAKEFILE) install
sub-plugin-install_subtargets: plugin/$(MAKEFILE) FORCE
	cd plugin/ && $(MAKE) -f $(MAKEFILE) install
sub-plugin-uninstall_subtargets-ordered: plugin/$(MAKEFILE) sub-lib-uninstall_subtargets-ordered  FORCE
	cd plugin/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-plugin-uninstall_subtargets: plugin/$(MAKEFILE) FORCE
	cd plugin/ && $(MAKE) -f $(MAKEFILE) uninstall
content/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) content/ || $(MKDIR) content/ 
	cd content/ && $(QMAKE) /var/tmp/portage/meego-extra/meego-app-email-0.2.9/work/meego-app-email-0.2.9/content/content.pro -o $(MAKEFILE)
sub-content-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) content/ || $(MKDIR) content/ 
	cd content/ && $(QMAKE) /var/tmp/portage/meego-extra/meego-app-email-0.2.9/work/meego-app-email-0.2.9/content/content.pro -o $(MAKEFILE)
sub-content: content/$(MAKEFILE) FORCE
	cd content/ && $(MAKE) -f $(MAKEFILE)
sub-content-make_default-ordered: content/$(MAKEFILE) sub-plugin-make_default-ordered  FORCE
	cd content/ && $(MAKE) -f $(MAKEFILE) 
sub-content-make_default: content/$(MAKEFILE) FORCE
	cd content/ && $(MAKE) -f $(MAKEFILE) 
sub-content-make_first-ordered: content/$(MAKEFILE) sub-plugin-make_first-ordered  FORCE
	cd content/ && $(MAKE) -f $(MAKEFILE) first
sub-content-make_first: content/$(MAKEFILE) FORCE
	cd content/ && $(MAKE) -f $(MAKEFILE) first
sub-content-all-ordered: content/$(MAKEFILE) sub-plugin-all-ordered  FORCE
	cd content/ && $(MAKE) -f $(MAKEFILE) all
sub-content-all: content/$(MAKEFILE) FORCE
	cd content/ && $(MAKE) -f $(MAKEFILE) all
sub-content-clean-ordered: content/$(MAKEFILE) sub-plugin-clean-ordered  FORCE
	cd content/ && $(MAKE) -f $(MAKEFILE) clean
sub-content-clean: content/$(MAKEFILE) FORCE
	cd content/ && $(MAKE) -f $(MAKEFILE) clean
sub-content-distclean-ordered: content/$(MAKEFILE) sub-plugin-distclean-ordered  FORCE
	cd content/ && $(MAKE) -f $(MAKEFILE) distclean
sub-content-distclean: content/$(MAKEFILE) FORCE
	cd content/ && $(MAKE) -f $(MAKEFILE) distclean
sub-content-install_subtargets-ordered: content/$(MAKEFILE) sub-plugin-install_subtargets-ordered  FORCE
	cd content/ && $(MAKE) -f $(MAKEFILE) install
sub-content-install_subtargets: content/$(MAKEFILE) FORCE
	cd content/ && $(MAKE) -f $(MAKEFILE) install
sub-content-uninstall_subtargets-ordered: content/$(MAKEFILE) sub-plugin-uninstall_subtargets-ordered  FORCE
	cd content/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-content-uninstall_subtargets: content/$(MAKEFILE) FORCE
	cd content/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: meego-app-email.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		common.pri \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile meego-app-email.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
common.pri:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile meego-app-email.pro

qmake_all: sub-lib-qmake_all sub-plugin-qmake_all sub-content-qmake_all FORCE

make_default: sub-lib-make_default-ordered sub-plugin-make_default-ordered sub-content-make_default-ordered FORCE
make_first: sub-lib-make_first-ordered sub-plugin-make_first-ordered sub-content-make_first-ordered FORCE
all: sub-lib-all-ordered sub-plugin-all-ordered sub-content-all-ordered FORCE
clean: sub-lib-clean-ordered sub-plugin-clean-ordered sub-content-clean-ordered FORCE
distclean: sub-lib-distclean-ordered sub-plugin-distclean-ordered sub-content-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-lib-install_subtargets-ordered sub-plugin-install_subtargets-ordered sub-content-install_subtargets-ordered FORCE
uninstall_subtargets: sub-lib-uninstall_subtargets-ordered sub-plugin-uninstall_subtargets-ordered sub-content-uninstall_subtargets-ordered FORCE

dist:
	rm -fR meego-app-email-0.2.9 && git clone . meego-app-email-0.2.9 && rm -fR meego-app-email-0.2.9/.git && rm -f meego-app-email-0.2.9/.gitignore && mkdir -p meego-app-email-0.2.9/ts && lupdate *.qml settings/*.qml settings/*.js -ts meego-app-email-0.2.9/ts/meego-app-email.ts && tar jcpvf meego-app-email-0.2.9.tar.bz2 meego-app-email-0.2.9 && rm -fR meego-app-email-0.2.9

sub-lib-check_ordered: lib/$(MAKEFILE)
	cd lib/ && $(MAKE) -f $(MAKEFILE) check
sub-plugin-check_ordered: plugin/$(MAKEFILE) sub-lib-check_ordered 
	cd plugin/ && $(MAKE) -f $(MAKEFILE) check
sub-content-check_ordered: content/$(MAKEFILE) sub-plugin-check_ordered 
	cd content/ && $(MAKE) -f $(MAKEFILE) check
check: sub-lib-check_ordered sub-plugin-check_ordered sub-content-check_ordered

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install_qmlfiles: FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/meego-app-email/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/meego-app-email/ 
	-$(INSTALL_FILE) /var/tmp/portage/meego-extra/meego-app-email-0.2.9/work/meego-app-email-0.2.9/AccountPage.qml $(INSTALL_ROOT)/usr/share/meego-app-email/
	-$(INSTALL_FILE) /var/tmp/portage/meego-extra/meego-app-email-0.2.9/work/meego-app-email-0.2.9/AccountViewToolbar.qml $(INSTALL_ROOT)/usr/share/meego-app-email/
	-$(INSTALL_FILE) /var/tmp/portage/meego-extra/meego-app-email-0.2.9/work/meego-app-email-0.2.9/AddAttachmentToolbar.qml $(INSTALL_ROOT)/usr/share/meego-app-email/
	-$(INSTALL_FILE) /var/tmp/portage/meego-extra/meego-app-email-0.2.9/work/meego-app-email-0.2.9/AddAttachmentView.qml $(INSTALL_ROOT)/usr/share/meego-app-email/
	-$(INSTALL_FILE) /var/tmp/portage/meego-extra/meego-app-email-0.2.9/work/meego-app-email-0.2.9/AddRecipient.qml $(INSTALL_ROOT)/usr/share/meego-app-email/
	-$(INSTALL_FILE) /var/tmp/portage/meego-extra/meego-app-email-0.2.9/work/meego-app-email-0.2.9/AttachmentPicker.qml $(INSTALL_ROOT)/usr/share/meego-app-email/
	-$(INSTALL_FILE) /var/tmp/portage/meego-extra/meego-app-email-0.2.9/work/meego-app-email-0.2.9/AttachmentPill.qml $(INSTALL_ROOT)/usr/share/meego-app-email/
	-$(INSTALL_FILE) /var/tmp/portage/meego-extra/meego-app-email-0.2.9/work/meego-app-email-0.2.9/AttachmentView.qml $(INSTALL_ROOT)/usr/share/meego-app-email/
	-$(INSTALL_FILE) /var/tmp/portage/meego-extra/meego-app-email-0.2.9/work/meego-app-email-0.2.9/Composer.qml $(INSTALL_ROOT)/usr/share/meego-app-email/
	-$(INSTALL_FILE) /var/tmp/portage/meego-extra/meego-app-email-0.2.9/work/meego-app-email-0.2.9/ComposerView.qml $(INSTALL_ROOT)/usr/share/meego-app-email/
	-$(INSTALL_FILE) /var/tmp/portage/meego-extra/meego-app-email-0.2.9/work/meego-app-email-0.2.9/EmailAddress.qml $(INSTALL_ROOT)/usr/share/meego-app-email/
	-$(INSTALL_FILE) /var/tmp/portage/meego-extra/meego-app-email-0.2.9/work/meego-app-email-0.2.9/EmailButton.qml $(INSTALL_ROOT)/usr/share/meego-app-email/
	-$(INSTALL_FILE) /var/tmp/portage/meego-extra/meego-app-email-0.2.9/work/meego-app-email-0.2.9/EmailHeader.qml $(INSTALL_ROOT)/usr/share/meego-app-email/
	-$(INSTALL_FILE) /var/tmp/portage/meego-extra/meego-app-email-0.2.9/work/meego-app-email-0.2.9/EmailRecipientEntry.qml $(INSTALL_ROOT)/usr/share/meego-app-email/
	-$(INSTALL_FILE) /var/tmp/portage/meego-extra/meego-app-email-0.2.9/work/meego-app-email-0.2.9/EmailSpinner.qml $(INSTALL_ROOT)/usr/share/meego-app-email/
	-$(INSTALL_FILE) /var/tmp/portage/meego-extra/meego-app-email-0.2.9/work/meego-app-email-0.2.9/FolderListMenu.qml $(INSTALL_ROOT)/usr/share/meego-app-email/
	-$(INSTALL_FILE) /var/tmp/portage/meego-extra/meego-app-email-0.2.9/work/meego-app-email-0.2.9/FolderListView.qml $(INSTALL_ROOT)/usr/share/meego-app-email/
	-$(INSTALL_FILE) /var/tmp/portage/meego-extra/meego-app-email-0.2.9/work/meego-app-email-0.2.9/FolderListViewToolbar.qml $(INSTALL_ROOT)/usr/share/meego-app-email/
	-$(INSTALL_FILE) /var/tmp/portage/meego-extra/meego-app-email-0.2.9/work/meego-app-email-0.2.9/main.qml $(INSTALL_ROOT)/usr/share/meego-app-email/
	-$(INSTALL_FILE) /var/tmp/portage/meego-extra/meego-app-email-0.2.9/work/meego-app-email-0.2.9/ReadingView.qml $(INSTALL_ROOT)/usr/share/meego-app-email/
	-$(INSTALL_FILE) /var/tmp/portage/meego-extra/meego-app-email-0.2.9/work/meego-app-email-0.2.9/ReadingViewToolbar.qml $(INSTALL_ROOT)/usr/share/meego-app-email/
	-$(INSTALL_FILE) /var/tmp/portage/meego-extra/meego-app-email-0.2.9/work/meego-app-email-0.2.9/SortFilter.qml $(INSTALL_ROOT)/usr/share/meego-app-email/
	-$(INSTALL_FILE) /var/tmp/portage/meego-extra/meego-app-email-0.2.9/work/meego-app-email-0.2.9/ToolbarButton.qml $(INSTALL_ROOT)/usr/share/meego-app-email/
	-$(INSTALL_FILE) /var/tmp/portage/meego-extra/meego-app-email-0.2.9/work/meego-app-email-0.2.9/ToolbarDivider.qml $(INSTALL_ROOT)/usr/share/meego-app-email/
	-$(INSTALL_FILE) /var/tmp/portage/meego-extra/meego-app-email-0.2.9/work/meego-app-email-0.2.9/VerticalAligner.qml $(INSTALL_ROOT)/usr/share/meego-app-email/
	-$(INSTALL_DIR) /var/tmp/portage/meego-extra/meego-app-email-0.2.9/work/meego-app-email-0.2.9/settings $(INSTALL_ROOT)/usr/share/meego-app-email/


uninstall_qmlfiles:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/meego-app-email/AccountPage.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/meego-app-email/AccountViewToolbar.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/meego-app-email/AddAttachmentToolbar.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/meego-app-email/AddAttachmentView.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/meego-app-email/AddRecipient.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/meego-app-email/AttachmentPicker.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/meego-app-email/AttachmentPill.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/meego-app-email/AttachmentView.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/meego-app-email/Composer.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/meego-app-email/ComposerView.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/meego-app-email/EmailAddress.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/meego-app-email/EmailButton.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/meego-app-email/EmailHeader.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/meego-app-email/EmailRecipientEntry.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/meego-app-email/EmailSpinner.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/meego-app-email/FolderListMenu.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/meego-app-email/FolderListView.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/meego-app-email/FolderListViewToolbar.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/meego-app-email/main.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/meego-app-email/ReadingView.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/meego-app-email/ReadingViewToolbar.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/meego-app-email/SortFilter.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/meego-app-email/ToolbarButton.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/meego-app-email/ToolbarDivider.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/meego-app-email/VerticalAligner.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/meego-app-email/settings
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/meego-app-email/ 


install_desktop: FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/meego-ux-settings/apps/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/meego-ux-settings/apps/ 
	-$(INSTALL_FILE) /var/tmp/portage/meego-extra/meego-app-email-0.2.9/work/meego-app-email-0.2.9/email-settings.desktop $(INSTALL_ROOT)/usr/share/meego-ux-settings/apps/


uninstall_desktop:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/meego-ux-settings/apps/email-settings.desktop
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/meego-ux-settings/apps/ 


install_schemas: FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/etc/gconf/schemas/ || $(MKDIR) $(INSTALL_ROOT)/etc/gconf/schemas/ 
	-$(INSTALL_FILE) /var/tmp/portage/meego-extra/meego-app-email-0.2.9/work/meego-app-email-0.2.9/meego-app-email.schemas $(INSTALL_ROOT)/etc/gconf/schemas/


uninstall_schemas:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/etc/gconf/schemas/meego-app-email.schemas
	-$(DEL_DIR) $(INSTALL_ROOT)/etc/gconf/schemas/ 


install: install_subtargets install_qmlfiles install_desktop install_schemas  FORCE

uninstall: uninstall_qmlfiles uninstall_desktop uninstall_schemas  uninstall_subtargets FORCE

FORCE:

